// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_notBad = new UnifiedAchievement("NotBad",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIp-yU8PkEEAIQAQ"
#else
            "NotBad"
#endif
            );

        public static UnifiedAchievement NotBad
        {
            get { return s_notBad; }
        }

        private static readonly UnifiedAchievement s_thatsOnlytheBeginning = new UnifiedAchievement("ThatsOnlytheBeginning",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIp-yU8PkEEAIQAg"
#else
            "ThatsOnlytheBeginning"
#endif
            );

        public static UnifiedAchievement ThatsOnlytheBeginning
        {
            get { return s_thatsOnlytheBeginning; }
        }

        private static readonly UnifiedAchievement s_killthemAll = new UnifiedAchievement("KillthemAll",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIp-yU8PkEEAIQCA"
#else
            "KillthemAll"
#endif
            );

        public static UnifiedAchievement KillthemAll
        {
            get { return s_killthemAll; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_notBad,
            s_thatsOnlytheBeginning,
            s_killthemAll,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "NotBad", s_notBad },
            { "ThatsOnlytheBeginning", s_thatsOnlytheBeginning },
            { "KillthemAll", s_killthemAll }
        };
    }
}
